In [2]:
import numpy as np, matplotlib.pyplot as plt, pandas as pd, seaborn as sns

import sys
sys.path.append('/ahg/regevdata/projects/CRISPR-libraries/prj2/evolution/abe8e/src/')
import _config, _lib

sys.path.append('/home/unix/maxwshen/')
from mylib import util

notebook_nm = 'fig_rising_star'
results_dir = _config.RESULTS_PLACE + f'{notebook_nm}/'
util.ensure_dir_exists(results_dir)

Using data folder:
 /ahg/regevdata/projects/CRISPR-libraries/prj2/evolution/abe8e/data/

In [3]:
# p2 only

In [24]:
## Load data

fitness_df = pd.read_csv('/ahg/regevdata/projects/CRISPR-libraries/prj2/evolution/abe8e/out/_fitness_pt/fullgt_fitness.csv', index_col = 0)

fq_df = pd.read_csv(f'/ahg/regevdata/projects/CRISPR-libraries/prj2/evolution/abe8e/out/data_multi/pv_groundtruth_0.0pct_t5_p2.csv')

fq_df['Genotype'] = [_lib.full_to_abbrev(s) for s in fq_df['Full genotype']]

print(fq_df.columns)
print(fitness_df.columns)

df = fitness_df.merge(fq_df, on = 'Genotype')
df = df.sort_values(by = 'Fitness', ascending = False)

display(df.head())

tcols = [col for col in df.columns if col[0] == 't']

df['Num. nonzero timepoints'] = df[tcols].astype(bool).apply(sum, axis = 'columns')

df.to_csv(results_dir + f'merged_fitness_fq.csv')

Index(['Full genotype', 't01', 't02', 't03', 't04', 't05', 't06', 't07', 't08',
       't09', 't10', 't11', 't12', 't13', 't14', 't15', 't16', 't17', 't18',
       't19', 't20', 't41', 't42', 't43', 't44', 't45', 't46', 't47', 't48',
       't49', 't86', 't87', 't88', 't89', 't90', 't91', 't92', 'Genotype'],
      dtype='object')
Index(['Genotype', 'Fitness'], dtype='object')

,Genotype,Fitness,Full genotype,t01,t02,t03,t04,t05,t06,t07,...,t47,t48,t49,t86,t87,t88,t89,t90,t91,t92
0,..G..L........SRN.....Y....,155.893692,"1 .,23 .,26 G,48 .,55 .,74 L,77 .,82 .,84 .,85...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000684,0.005783
1,..G...V.....A.SRN.....Y....,154.018341,"1 .,23 .,26 G,48 .,55 .,74 .,77 V,82 .,84 .,85...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001140,0.009262
2,..G..G......A.SRN.....Y....,139.318253,"1 .,23 .,26 G,48 .,55 .,74 G,77 .,82 .,84 .,85...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001709,0.012459
3,..G..G........SRN.....Y....,126.900200,"1 .,23 .,26 G,48 .,55 .,74 G,77 .,82 .,84 .,85...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000684,0.004843
4,..G..V......A.SRN.....Y....,126.571991,"1 .,23 .,26 G,48 .,55 .,74 V,77 .,82 .,84 .,85...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001823,0.012083

In [25]:
cols = ['Genotype', 'Fitness', 't92', 'Num. nonzero timepoints']

df[cols].iloc[:14]

                       Genotype     Fitness       t92  Num. nonzero timepoints
0   ..G..L........SRN.....Y....  155.893692  0.005783                        2
1   ..G...V.....A.SRN.....Y....  154.018341  0.009262                        2
2   ..G..G......A.SRN.....Y....  139.318253  0.012459                        2
3   ..G..G........SRN.....Y....  126.900200  0.004843                        2
4   ..G..V......A.SRN.....Y....  126.571991  0.012083                        2
5   ..G.....L...A.SRN.....Y....   98.080093  0.015139                        2
6   ..G..V........SRN.....Y....   86.107826  0.003902                        2
7   ..G........G..SRN.....Y....   75.425926  0.003714                        2
8   ..G.....LQ..A.SRN.....Y....   68.525261  0.003291                        2
9   ..G..L......A.SRN.....Y....   68.267151  0.015562                        3
10  ..G........GA.SRN.....Y....   61.839821  0.026187                        3
11  ..G.P.......A.SRN.....Y....   58.364822  0.004513                        2
12  ..G...V.......SRN.....Y....   57.062630  0.015421                        3
13  ..G.........A.SRN.....Y....   55.651089  0.206488                        5